export enum Configuration {
  PORT = 'PORT',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  JWT_SECRET = 'JWT_SECRET',
  EXPIRY_TOKEN = 'EXPIRY_TOKEN',
  ALLOWED_ORIGIN = 'ALLOWED_ORIGIN',
}
